services:
  - type: worker
    name: meme-scanner-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ALERT_CHAT_ID
        sync: false
      - key: TWITTER_BEARER_TOKEN
        sync: fals
